In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
import pickle

In [2]:
with open('session_18_graph.pickle', 'rb') as f:
    G = pickle.load(f)
G.remove_edge(3, 9)

In [3]:
adjacency_matrix = nx.to_numpy_array(G)

In [4]:
adjacency_matrix

array([[0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1

In [5]:
adjacency_matrix = nx.to_numpy_array(G)

In [6]:
adjacency_matrix

array([[0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1

In [7]:
transition_vector = np.array([.2 if i in G[0] else 0 for i in G.nodes])

In [8]:
v2 = np.array([1 if i in G[0] else 0 for i in G.nodes]) * .2

In [9]:
v2

array([0. , 0. , 0. , 0.2, 0.2, 0. , 0.2, 0.2, 0. , 0. , 0. , 0. , 0. ,
       0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. ])

In [10]:
v3 = adjacency_matrix[:, 0] * .2

In [11]:
v4 = adjacency_matrix[:, 0] / adjacency_matrix[:, 0].sum()

In [12]:
for v in [v2, v3, v4]:
    assert np.array_equal(v, transition_vector)

In [13]:
adjacency_matrix.shape

(31, 31)

In [14]:
adjacency_matrix / adjacency_matrix.sum(axis=0)

array([[0.        , 0.        , 0.        , 0.125     , 0.16666667,
        0.        , 0.2       , 0.14285714, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.16666667, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.14285714, 0.125     , 0.16666667,
        0.25      , 0.2       , 0.14285714, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.16666667, 0.        , 0.125     , 0.16666667,
        0.25      , 0.2       , 0.14285714, 0.        , 0.        ,
      

In [15]:
transition_matrix = _

In [16]:
assert np.array_equal(transition_matrix[:, 0], transition_vector)

In [17]:
v = np.ones(31) / 31

In [18]:
v

array([0.03225806, 0.03225806, 0.03225806, 0.03225806, 0.03225806,
       0.03225806, 0.03225806, 0.03225806, 0.03225806, 0.03225806,
       0.03225806, 0.03225806, 0.03225806, 0.03225806, 0.03225806,
       0.03225806, 0.03225806, 0.03225806, 0.03225806, 0.03225806,
       0.03225806, 0.03225806, 0.03225806, 0.03225806, 0.03225806,
       0.03225806, 0.03225806, 0.03225806, 0.03225806, 0.03225806,
       0.03225806])

In [19]:
for _ in range(10):
    v = transition_matrix @ v

In [20]:
for i in [12, 3]:
    print(f"The probability of winding up in Town {i} is {v[i]:.3f}.")

The probability of winding up in Town 12 is 0.051.
The probability of winding up in Town 3 is 0.047.


In [21]:
for i in range(31):
    prob = transition_matrix[0][i] / 31
    if not prob:
        continue
    print(f"Probability of starting in Town {i} and driving to Town 0 is " f"{prob:.2}")
print("\nAll remaining transition probabilities are 0.0")

Probability of starting in Town 3 and driving to Town 0 is 0.004
Probability of starting in Town 4 and driving to Town 0 is 0.0054
Probability of starting in Town 6 and driving to Town 0 is 0.0065
Probability of starting in Town 7 and driving to Town 0 is 0.0046
Probability of starting in Town 13 and driving to Town 0 is 0.0054

All remaining transition probabilities are 0.0


In [22]:
np.random.seed(0)
prob = sum(transition_matrix[0][i]/31 for i in range(31))

In [23]:
prob

0.02584485407066052

In [24]:
stop_1_probabilities = transition_matrix @ v

In [25]:
prob = stop_1_probabilities[12]

In [26]:
prob

0.05103381882601836

In [27]:
np.random.seed(0)
stop_2_probabilities = transition_matrix @ transition_matrix @ v
prob = stop_2_probabilities[12]

In [28]:
prob

0.05107950698506779

In [31]:
temp = transition_matrix @ stop_1_probabilities

In [33]:
temp[3]

0.04721131357221504

In [34]:
stop_2_probabilities

array([0.02969096, 0.03506199, 0.04126412, 0.04721131, 0.03513052,
       0.02336429, 0.02932618, 0.04135133, 0.03367103, 0.02079128,
       0.01397051, 0.02758314, 0.05107951, 0.03787772, 0.04418468,
       0.02532996, 0.03757864, 0.04479964, 0.01942413, 0.02602708,
       0.01951335, 0.0196396 , 0.01882367, 0.03871202, 0.02579421,
       0.04646317, 0.01998644, 0.039917  , 0.0397154 , 0.03976244,
       0.02695471])

In [35]:
centrality = nx.pagerank(G)[12]

In [36]:
centrality

0.047824993453950214